services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5001:5001"
    env_file:
      - ./order-service/.env
    depends_on:
      - mongo

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "5002:5002"
    env_file:
      - ./restaurant-service/.env
    depends_on:
      - mongo

volumes:
  mongo_data:
